### ISSUE TITLE
requests.exceptions.HTTPError: 403 Client Error: Forbidden

### ISSUE THREAD

**Issue by sevmardi** [ipinfo/django#13]
have the following 
```
ip_data = ipinfo.getHandler(self.ipinfo_token, **self.ipinfo_settings)
ip_data = ip_data.getDetails(ip_address)
```

the following error returns 
`requests.exceptions.HTTPError: 403 Client Error: Forbidden`

**Comment by sevmardi** [comment]
P.S. the api token is working just fine.

**Comment by sevmardi** [comment]
@UmanShahzad  Thanks for quick response. No, the issue was related to this library as ipinfo was working just fine.. but It turns out we were having some other internal issues..🤦‍♂️ this is now resolved.

**Comment by UmanShahzad** [comment]
Ok thanks @sevmardi , that's what I expected, possibly some messy proxy or some other configuration :)
