### ISSUE TITLE
unresolved import 'ipinfo'

### ISSUE THREAD

**Issue by Barna-154** [ipinfo/django#17]
hie i am trying to import the ipinfo module in my django views but its giving me an error 'unresolved import 'ipinfo'..

![image](https://user-images.githubusercontent.com/42910304/122184765-d76e3780-ce8c-11eb-8a46-dbee85811d67.png)

**Comment by UmanShahzad** [comment]
Hi @Barna-154, this is likely an environment/configuration issue on your side. Make sure that the context in which this error is shown has properly been exposed to `pip install ipinfo_django`.

**Comment by Barna-154** [comment]
hie @UmanShahzad my environment is exposed to pip install ipinfo_django . below is a snap of my pip freeze 
![image](https://user-images.githubusercontent.com/42910304/122189737-79901e80-ce91-11eb-98e8-993198993414.png)

**Comment by UmanShahzad** [comment]
@Barna-154 is your IDE exposed to it though? Your IDE might be using a different python environment than the one you're running `pip freeze` from.

**Comment by Barna-154** [comment]
hie @UmanShahzad i checked on my environments because i am using vscode in ubuntu on wsl2, so it was that, the python on the windows was the working on vscode rather the one on ubuntu. thank you for the higlight
