### ISSUE TITLE
CSP Blocking requests

### ISSUE THREAD

**Issue by ayy-em** [ipinfo/django#22]
I'm using django 3.2.4 and ipinfo correctly parses requests done when testing on a local environment, but not in prod (deployed on google app engine). I assume it has to do with CSP blocking outgoing requests, but i added `ipinfo.io` to allowed request URLs, but it still defaults to showing every request as one made from the US (Mountain View). Any ideas?

**Comment by UmanShahzad** [comment]
Hey, which version of the ipinfo-django package are you using? Can you use 1.2.0 and let me know if it still happens?

**Comment by ayy-em** [comment]
@UmanShahzad indeed, 1.2.0 seems to have fixed that - thanks!
