### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: WSGI application 'Mysite.wsgi.application' could not be loaded; Error importing module.

### ISSUE THREAD

**Issue by hesamdavarpanah** [ipinfo/django#27]
After update package ipinfo_django 1.2.0 to 1.3.0, It return me this error:

from ipinfo_django.ip_selector.default import DefaultIPSelector
ModuleNotFoundError: No module named 'ipinfo_django.ip_selector'
...
django.core.exceptions.ImproperlyConfigured: WSGI application 'Backend.wsgi.application' could not be loaded; Error importing module.

I already added 'ipinfo_django.middleware.IPinfo' in MIDDLEWARE

**Comment by UmanShahzad** [comment]
Apologies. It was missing from `setup.py`, and is added there now. Please upgrade to 1.3.1 and see if that fixes things. Thank you!
