### ISSUE TITLE
asgiref version conflict with Django 4.0.7+

### ISSUE THREAD

**Issue by ayy-em** [ipinfo/django#29]
Reproduce:
- Update Django to 4.0.7+
- It requires `asgiref<4` and `asgiref>=3.4.1`
- however, `asgiref` past 3.2.1 makes django throw an ipinfo exception: `'IPinfo' object has no attribute '_is_coroutine'`

**Comment by UmanShahzad** [comment]
@rm-Umar can you check this?

**Comment by UmanShahzad** [comment]
Can you try again in `2.0.0`? Note that a breaking change was made; the synchronous middleware was renamed to `IPinfoMiddleware`.

**Comment by UmanShahzad** [comment]
https://pypi.org/project/ipinfo-django/2.0.0/

**Comment by ayy-em** [comment]
@UmanShahzad seems to have resolved the issue! thanks guys

**Comment by UmanShahzad** [comment]
Beautiful!
